# npm-check-updates configuration used by yarn deps:check && yarn deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates
reject: [
    # Add here exclusions on packages if any
    # i.e: '@types/node'

    "execa",

    # till eslint 8 is ready
    "eslint",

    # Too early cause in esm
    "is-port-reachable"
]
