defaultSemverRangePrefix: ''

enableGlobalCache: false

nmMode: hardlinks-global

nodeLinker: node-modules

packageExtensions:
  apollo-server-micro@*:
    peerDependencies:
      graphql: ^15.6.1
  # This does not work, so I've set the dep in web-app
  #"react-markdown@*":
  #  peerDependenciesMeta:
  #    "@types/react":
  #      optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'

yarnPath: .yarn/releases/yarn-3.2.0-rc.14.cjs
